plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-minimal
title: Abdolraouf Rahmani
description: Committed and goal-driven student with academic knowdelge and intermediate experience spanning full range of
software engineering, hardware, scripting, testing, and technical marketing across multiple 
platforms and environments. 
